//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Domain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Domain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Domain", typeof(Domain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string ArticleBody {
            get {
                return ResourceManager.GetString("ArticleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headline.
        /// </summary>
        public static string ArticleHeadline {
            get {
                return ResourceManager.GetString("ArticleHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ArticleName {
            get {
                return ResourceManager.GetString("ArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name Id.
        /// </summary>
        public static string CategoryNameId {
            get {
                return ResourceManager.GetString("CategoryNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string CategoryProducts {
            get {
                return ResourceManager.GetString("CategoryProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type name too long..
        /// </summary>
        public static string ContactTypeNameLengthError {
            get {
                return ResourceManager.GetString("ContactTypeNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact too long..
        /// </summary>
        public static string ContactValueLengthError {
            get {
                return ResourceManager.GetString("ContactValueLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string EntityPrimaryKey {
            get {
                return ResourceManager.GetString("EntityPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, Lastname.
        /// </summary>
        public static string FirstLastname {
            get {
                return ResourceManager.GetString("FirstLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name too long..
        /// </summary>
        public static string FirstnameLengthError {
            get {
                return ResourceManager.GetString("FirstnameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image filename.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains invalid characters.
        /// </summary>
        public static string ImageUrlInvalid {
            get {
                return ResourceManager.GetString("ImageUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes gluten.
        /// </summary>
        public static string IngredientHasGluten {
            get {
                return ResourceManager.GetString("IngredientHasGluten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes allergenes.
        /// </summary>
        public static string IngredientIsAllergenic {
            get {
                return ResourceManager.GetString("IngredientIsAllergenic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        public static string IngredientName {
            get {
                return ResourceManager.GetString("IngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient name Id.
        /// </summary>
        public static string IngredientNameId {
            get {
                return ResourceManager.GetString("IngredientNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number.
        /// </summary>
        public static string InvoiceId {
            get {
                return ResourceManager.GetString("InvoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment received date.
        /// </summary>
        public static string InvoicePaymentReceived {
            get {
                return ResourceManager.GetString("InvoicePaymentReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sum.
        /// </summary>
        public static string InvoiceTotalSum {
            get {
                return ResourceManager.GetString("InvoiceTotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last, Firstname.
        /// </summary>
        public static string LastFirstname {
            get {
                return ResourceManager.GetString("LastFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name too long..
        /// </summary>
        public static string LastnameLengthError {
            get {
                return ResourceManager.GetString("LastnameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilang string.
        /// </summary>
        public static string MultiLangStringId {
            get {
                return ResourceManager.GetString("MultiLangStringId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string MultiLangStringOwner {
            get {
                return ResourceManager.GetString("MultiLangStringOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion date.
        /// </summary>
        public static string OrderCompletedDate {
            get {
                return ResourceManager.GetString("OrderCompletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up date.
        /// </summary>
        public static string OrderForDate {
            get {
                return ResourceManager.GetString("OrderForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up date is required.
        /// </summary>
        public static string OrderForDateRequired {
            get {
                return ResourceManager.GetString("OrderForDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order nr..
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string OrderInvoice {
            get {
                return ResourceManager.GetString("OrderInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed date.
        /// </summary>
        public static string OrderPlacedDate {
            get {
                return ResourceManager.GetString("OrderPlacedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderProductQuantity {
            get {
                return ResourceManager.GetString("OrderProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity can be between {1} to {2} kg. For orders bigger than that, contact us..
        /// </summary>
        public static string OrderProductQunatityRange {
            get {
                return ResourceManager.GetString("OrderProductQunatityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string OrderUser {
            get {
                return ResourceManager.GetString("OrderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Person_Date2 {
            get {
                return ResourceManager.GetString("Person_Date2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        public static string Person_DateTime2 {
            get {
                return ResourceManager.GetString("Person_DateTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Person_Time2 {
            get {
                return ResourceManager.GetString("Person_Time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ProductBasePrice {
            get {
                return ResourceManager.GetString("ProductBasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be between {1} and {2}.
        /// </summary>
        public static string ProductBasePriceRange {
            get {
                return ResourceManager.GetString("ProductBasePriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string ProductIngredients {
            get {
                return ResourceManager.GetString("ProductIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string TranslationCulture {
            get {
                return ResourceManager.GetString("TranslationCulture", resourceCulture);
            }
        }
    }
}
